name: Build APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Apktool
      run: |
        sudo apt-get update
        sudo apt-get install -y apktool

    - name: Clean problematic resource files
      run: |
        find . -name "*.bak" -delete
        find . -name "*\$*" -delete

    - name: Build APK with Apktool
      run: |
        mkdir -p dist
        apktool b . -o dist/ProxyPro_release.apk --force-all

    - name: Upload Built APK
      uses: actions/upload-artifact@v4
      with:
        name: ProxyPro-Signed
        path: dist/ProxyPro_release.apk
